url: https://binwoods.github.io
# baseurl: /agency-jekyll-theme/
host: localhost

# Site settings
title: 冰冰工作室
email: miss.wbingbing@gmail.com
description: "Design Comes From Life,Pursue Inspiration In Life"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: c1f5c4
  secondary: 99ffcc
  secondary-dark: 355c7d
  title: ffffff
  links: 000000
  links-hover: 000066

# Team names, titles and social links
people:
- name: 王冰冰
  pic: 1
  position: 首席设计师
  social:
    - title: weibo
      url: #
    - title: linkedin
      url: #
    - title: facebook
      url: #



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# 注:这里写工作室的账号网址，个人的已在Team里填写.
social:
  - title: weibo
    url: 
  - title: pinterest
    url: 
  - title: linkedin
    url: 
  - title: facebook 
    url: 
  - title: github
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
